### ISSUE TITLE
[bug] If the Spawner's Entity Data is Empty, it still says there's a pig mob inside it.

### ISSUE THREAD

**Issue by CalamitousEnd** [CrimsonFluff/Silk-Spawners#1]
So basically, I created a Datapack that let's Monster Spawners be craftable, the problem with this is that once you get the spawner it says "mob: pig" which it should instead say "mob: NONE". Is there any way to address this?

**Comment by CrimsonFluff** [comment]
when you craft a spawner, what does the nbt data say?  can you send me a screenshot

**Comment by CalamitousEnd** [comment]
![2021-11-11_14 08 24](https://user-images.githubusercontent.com/41867693/141354945-375855f1-1635-46dc-b748-a8ea7176933b.png)

This spawner should be saying "mob: NONE" right?

**Comment by CalamitousEnd** [comment]
![2021-11-11_14 10 09](https://user-images.githubusercontent.com/41867693/141355078-a3de667b-9870-4b5a-9084-6a71fe8a56cd.png)

Proof that the spawner is indeed empty. :)

**Comment by CrimsonFluff** [comment]
I didnt need proof I needed the nbt tag itself  like {isVisible:1} sort of thing

but I'll take a looksy anyways

**Comment by CalamitousEnd** [comment]
Thank you, sorry for being a pain in the butt.

**Comment by CrimsonFluff** [comment]
out of interest do you craft different spawners or provide spawn eggs?  like how does the player set the type of spawner?

I also think the bug is a silly oversight of mine, lol

**Comment by CalamitousEnd** [comment]
So, I craft an Empty Spawner using a Datapack and then you can buy different Spawn Eggs from Wandering Traders using a different mod that lets me change Villager Trades. :)

**Comment by CrimsonFluff** [comment]
one problem with the spawners is that placing an `empty` spawner instantly turns it into a pig spawner

thats because vanilla code says if it cant spawn the entity (in this case because the nbt `mob:id` is empty) then default to pig
this could probably be fixed, but its beyond my capability - I would literally have to replace spawner code with my own somehow - thats still a bit advanced for me...

**Comment by CrimsonFluff** [comment]
uploaded 1.16.5 and 1.17.1 changes to curseforge. may take a couple of hours to be approved  :-)

let me know if all is good

**Comment by CrimsonFluff** [comment]
theyve been approved

**Comment by CalamitousEnd** [comment]
It's definitely a lot better now. A bit tripped by the "mob: minecraft:" thing that comes up after you mine an empty spawner but I can live with that bug.

**Comment by CrimsonFluff** [comment]
that never happened for me?  I spawned an empty spawner.  In inventory it didnt say anything extra in the tooltip.  Jst the name of item like normal.  The moment I placed it, it changed to a pig spawner, so when I mined it, it said pig?

**Comment by CalamitousEnd** [comment]
It might've been a fluke. Let me see if I can recreate the bug.

**Comment by CalamitousEnd** [comment]
For clarification purposes this is the command I ran to give myself the Spawner in the first place for testing:

/give Calamitous_End minecraft:spawner{SpawnData:{id:{}},delay:299}

I placed down the spawner, did exactly as expected, the spawner was empty. When I mined it this happened:

![2021-11-11_17 37 46](https://user-images.githubusercontent.com/41867693/141380756-4703b7a9-c63b-48ac-829b-4ff38204bd17.png)

Placed it down, mined it again same thing repeated itself.

**Comment by CrimsonFluff** [comment]
i was using `minecraft:spawner`  - seems its more silly than I thought...

**Comment by CalamitousEnd** [comment]
When I craft spawners it's the same story because it crafts them with the same NBT data as what is used in the command above.

**Comment by CrimsonFluff** [comment]
ok - I need to make a better check - I'll have a bash at it 2moz, as its 11pm for me

**Comment by CrimsonFluff** [comment]
hopefully fixed this time, but I noticed 2 things:
1) using that command you posted causes continuous render errors in the debug log
2) placing the spawner still causes The ONE Probe to show `Pig` as the spawner type

Uploaded to CurseForge

**Comment by CalamitousEnd** [comment]
As a Modder myself, I can take a shot at trying to fix the error myself with the Rendering problem. This should be fixable with Mixins. No promises.

**Comment by CrimsonFluff** [comment]
feel free to offer your skills in any of my mods, im fairly new to modding
