### ISSUE TITLE
Mined spawners turn into pig spawners.

### ISSUE THREAD

**Issue by lerfis** [CrimsonFluff/Silk-Spawners#2]
Hi! just wanted to let you know that that the spawners i mine turn into pig spawnes when i try to place them back down. lemme know if there is any more info i can give for you to be able to fix this.

Cheers!

**Comment by CrimsonFluff** [comment]
forge, fabric, which version? are you using silk touch pick?

**Comment by CrimsonFluff** [comment]
Ive just tested all 3 Forge versions, they work as intended

**Comment by lerfis** [comment]
Hi, thanks for the quick reply.

1. Fabric https://www.curseforge.com/minecraft/mc-mods/crimson-silk-spawners-fabric/files 
2. SilkSpawners-1.18-Fabric-v1.0.0.jar
3. 1.18 and running on a Server.
4. YES.

Does the mod need to be installed on both server and client ?

**Comment by CrimsonFluff** [comment]
yes server and client

**Comment by lerfis** [comment]
Give me one moment, will recheck.

**Comment by lerfis** [comment]
no luck still does it, here's a vid

https://user-images.githubusercontent.com/1363068/144307978-e95fc7a6-9f45-4450-a24e-c9340b83c005.mp4

**Comment by CrimsonFluff** [comment]
does it work in single player?

**Comment by lerfis** [comment]
nope, not for me at least.

**Comment by CrimsonFluff** [comment]
see it works for me in dev environment

what version of fabric and loader are you using?

**Comment by lerfis** [comment]
fabric-api-0.43.1+1.18 Fabric Loader Version 12.8

**Comment by CrimsonFluff** [comment]
confirmed. it works in dev but not outside the dev environment

im most likely going to delete this mod

**Comment by lerfis** [comment]
that sucks, glad i could help atleast.

**Comment by CrimsonFluff** [comment]
yeah, thank you for your patience in testing  

this mod works outside the rules of chunk claiming and block protection
im just not happy with it

**Comment by CrimsonFluff** [comment]
mod deleted
